"""Increase project name length from 30 to 128

Revision ID: fdd4f3da166f
Revises: 9f15bb919fb6
Create Date: 2025-12-24 00:54:31.478706

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdd4f3da166f'
down_revision: Union[str, Sequence[str], None] = '9f15bb919fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name',
                    existing_type=sa.String(length=128),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    # ### end Alembic commands ###
