"""Create models

Revision ID: 5b1fc14e4516
Revises: 
Create Date: 2025-12-22 00:28:43.221305

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b1fc14e4516'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=True),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    )
    op.create_table('technology',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(length=120), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    )
    op.create_table('technology_version',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('technology_id', sa.Integer(), nullable=False),
                    sa.Column('version', sa.String(length=15), nullable=False),
                    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('technology_id', 'version'),
                    )
    op.create_table('project_technology_association',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('technology_version_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
                    sa.ForeignKeyConstraint(['technology_version_id'], ['technology_version.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'technology_version_id'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_technology_association')
    op.drop_table('technology_version')
    op.drop_table('technology')
    op.drop_table('project')
    # ### end Alembic commands ###
