"""Increase technology name and description lengths up to 128 and 255 respectively

Revision ID: 9f7fc5782f1f
Revises: fdd4f3da166f
Create Date: 2025-12-24 00:56:55.475377

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f7fc5782f1f'
down_revision: Union[str, Sequence[str], None] = 'fdd4f3da166f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology', 'name',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    op.alter_column('technology', 'description',
                    existing_type=sa.VARCHAR(length=120),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('technology_version', 'version',
                    existing_type=sa.VARCHAR(length=15),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology_version', 'version',
                    existing_type=sa.String(length=128),
                    type_=sa.VARCHAR(length=15),
                    existing_nullable=False)
    op.alter_column('technology', 'description',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=120),
                    existing_nullable=True)
    op.alter_column('technology', 'name',
                    existing_type=sa.String(length=128),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    # ### end Alembic commands ###
